function result = run_full_pipeline(cfg)
%RUN_FULL_PIPELINE Run both pipeline stages from a config struct.

if ~isfield(cfg, "dge_sheet") || strlength(string(cfg.dge_sheet)) == 0
    cfg.dge_sheet = "IO_Data";
end

splitResult = split_utilities_sector( ...
    cfg.io_xlsx_path, ...
    cfg.tech_summary_csv, ...
    cfg.split_output_xlsx, ...
    cfg.split_output_csv, ...
    cfg.split_summary_csv);

dgeResult = aggregate_for_dge( ...
    cfg.split_output_csv, ...
    cfg.oecd_xlsx, ...
    cfg.dge_workbook, ...
    cfg.dge_sheet, ...
    cfg.dge_output_xlsx, ...
    cfg.dge_output_csv, ...
    cfg.dge_validation_csv, ...
    cfg.dge_audit_csv, ...
    cfg.dge_output_workbook_copy);

result = struct("split", splitResult, "dge", dgeResult);
end

