%% Compare scenarios (multiple lines per plot) + save all figures
clearvars; close all; clc

addpath('C:\dynare\6.1\matlab')

%% Settings
casScenarios      = {'Baseline','NZ','NZ_constEE','Finance_RG'};   % <-- edit
caslegendentries  = {'PDP8','Net Zero','NZ const EE','Finance Gov'}; % <-- edit
casLinetypes      = {'-','--',':','-.'};                           % <-- edit
Tplot             = 50;                                            % years to plot (rows)
outdir            = fullfile(pwd,'Figures_compare');
if ~exist(outdir,'dir'); mkdir(outdir); end

%% Load CSVs
sversion = '';  % output-CSV suffix written by RunSimulations (sSensitivity); this script does not call setup_paths, so report_version_suffix() is not available here
dsall = struct();
for i = 1:numel(casScenarios)
    sScen = casScenarios{i};
    fn = fullfile('../../ExcelFiles','Output',[sScen sversion '.csv']);
    assert(isfile(fn), 'Missing file: %s', fn);
    dsall.(sScen) = readtable(fn);
end

%% Define plots (one figure each; all scenarios overlaid)
plots = {};

% 1) Emissions (Indexed, base=300)
plots{end+1} = struct( ...
    'name','Emissions_Indexed', ...
    'ylabel','Index (Base = 300)', ...
    'func', @(ds,T) ds.E_1(1:T)./ds.E_1(1)*300, ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Emissions (Indexed)' );

% 2) Annual GDP growth (%)
plots{end+1} = struct( ...
    'name','GDP_Growth', ...
    'ylabel','%', ...
    'func', @(ds,T) (ds.Y_1(2:T)./ds.Y_1(1:T-1)-1)*100, ...
    'xfunc', @(ds,T) ds.Year(2:T), ...
    'title','Annual GDP Growth (%)' );

% 3) Renewable energy share (%)
plots{end+1} = struct( ...
    'name','Renewable_Share', ...
    'ylabel','%', ...
    'func', @(ds,T) ds.Q_D_3_1(1:T)./(ds.Q_D_2_1(1:T)+ds.Q_D_3_1(1:T))*100, ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Renewable Energy Share (%)' );

% 4) Fossil energy production (index/level as in CSV)
plots{end+1} = struct( ...
    'name','Fossil_Energy_Production', ...
    'ylabel','Index', ...
    'func', @(ds,T) ds.Q_2_1(1:T), ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Fossil Energy Production' );

% 5) Renewable capital stock
plots{end+1} = struct( ...
    'name','Renewables_Capital', ...
    'ylabel','Index', ...
    'func', @(ds,T) ds.K_3_1(1:T), ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Renewables Capital' );

% 6) Agriculture share in VA (%)
plots{end+1} = struct( ...
    'name','VA_Share_Agriculture', ...
    'ylabel','%', ...
    'func', @(ds,T) (ds.P_1_1(1:T).*ds.Y_1_1(1:T)./ds.Y_1(1:T))*100, ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Agriculture Share in VA' );

% 7) Manufacturing share in VA (%)
plots{end+1} = struct( ...
    'name','VA_Share_Manufacturing', ...
    'ylabel','%', ...
    'func', @(ds,T) (ds.P_4_1(1:T).*ds.Y_4_1(1:T)./ds.Y_1(1:T))*100, ...
    'xfunc', @(ds,T) ds.Year(1:T), ...
    'title','Manufacturing Share in VA' );

%% Make & save all figures
for ip = 1:numel(plots)
    P = plots{ip};
    fig = figure('Name',P.name); hold on

    for i = 1:numel(casScenarios)
        sScen = casScenarios{i};
        ds = dsall.(sScen);

        T = min(Tplot, height(ds)); % safety
        x = P.xfunc(ds,T);
        y = P.func(ds,T);

        plot(x, y, casLinetypes{i}, 'LineWidth', 1.5);
    end

    ylabel({P.title, P.ylabel})
    legend(caslegendentries,'Location','best')
    grid on
    hold off

    save_my_figure(fig, P.name, outdir);
end

disp("All scenario comparison figures generated and saved.");

%% ---- local function (keep at end of file) ----
function save_my_figure(fig, name, outdir)
    % safe filename
    name = regexprep(name,'[^A-Za-z0-9_\-]','_');

    exportgraphics(fig, fullfile(outdir,[name '.png']), 'Resolution', 300);
    exportgraphics(fig, fullfile(outdir,[name '.pdf']), 'ContentType','vector');
end
