%% Online Training comparison: PDP8 finance variants vs Baseline
% Scenarios from Day 1 slide 7 (PDP8 pathway): PDP8_GF_A/B/C.
% Outputs: one relative-to-baseline figure per variable with all scenarios.

close all;

config = struct();
config.baselineName = "Baseline";
config.baselineLabel = "Baseline";
config.scenarioSpecs = table( ...
    ["PDP8_GF_A"; "PDP8_GF_B"; "PDP8_GF_C"], ...
    ["PDP8 GF A"; "PDP8 GF B"; "PDP8 GF C"], ...
    'VariableNames', {'Name', 'Label'});
config.plotStartYear = 2025;
config.plotEndYear = 2050;
config.plotSubfolder = 'ScenarioComparisons/OnlineTraining/PDP8_vs_Baseline';
config.chartTitlePrefix = "PDP8 variants vs Baseline";
config.exportPdf = true;
config.plotSpecs = table( ...
    ["I_1"; "r_G_3_1"; "r_FDI_3_1"; "K_G_3_1"; "K_FDI_3_1"; ...
     "Y_1"; "C_1"; "E_1"; "PE_1"], ...
    ["Total investment"; "Cost of public capital (renewables)"; ...
     "Cost of FDI capital (renewables)"; "Public renewable capital"; ...
     "FDI renewable capital"; "GDP"; "Consumption"; ...
     "Emissions"; "Emission price"], ...
    ["pct_deviation"; "difference"; "difference"; "pct_deviation"; ...
     "pct_deviation"; "pct_deviation"; "pct_deviation"; ...
     "pct_deviation"; "difference"], ...
    'VariableNames', {'Variable', 'Label', 'Deviation'});

run_online_training_comparison(config);
