%% Online Training comparison: NZ finance variants vs NZ baseline pathway
% Scenarios from Day 1 slide 7 (NZ pathway): NZ_GF_A/B/C.
% Outputs: one relative-to-baseline figure per variable with all scenarios.

close all;

config = struct();
config.baselineName = "Baseline"
config.baselineLabel = "revised PDP 9 high";
config.scenarioSpecs = table( ...
    ["NZ"; "NZ_GF_A"; "NZ_GF_B"; "NZ_GF_C"], ...
    ["NZ"; "NZ GF A"; "NZ GF B"; "NZ GF C"], ...
    'VariableNames', {'Name', 'Label'});
config.plotStartYear = 2025;
config.plotEndYear = 2050;
config.plotSubfolder = 'ScenarioComparisons/OnlineTraining/NZ_variants_vs_NZ';
config.chartTitlePrefix = "NZ variants vs NZ";
config.exportPdf = true;
config.plotSpecs = table( ...
    ["I_1"; "r_G_3_1"; "r_FDI_3_1"; "K_G_3_1"; "K_FDI_3_1"; ...
     "Y_1"; "C_1"; "E_1"; "PE_1"], ...
    ["Total investment"; "Cost of public capital (renewables)"; ...
     "Cost of FDI capital (renewables)"; "Public renewable capital"; ...
     "FDI renewable capital"; "GDP"; "Consumption"; ...
     "Emissions"; "Emission price"], ...
    ["pct_deviation"; "difference"; "difference"; "pct_deviation"; ...
     "pct_deviation"; "pct_deviation"; "pct_deviation"; ...
     "pct_deviation"; "difference"], ...
    'VariableNames', {'Variable', 'Label', 'Deviation'});

run_online_training_comparison(config);
