function strys = computeGovernmentExpenditureAndCapital(strys, strpar)
    for icoreg = 1:strpar.inbregions_p
        sreg = num2str(icoreg);
        strys.(['G_' sreg]) = ...
            strys.(['Q_U_' sreg]) * strys.(['P_D_' sreg]) / strys.(['P_' sreg]) + ...
            strys.(['M_F_' sreg]) * strys.(['P_F_' sreg]) / strys.(['P_' sreg]) - ...
            strys.(['C_' sreg]) - strys.(['I_' sreg]) - ...
            (strpar.iSecHouse_p == 0) * strys.(['PH_' sreg]) / strys.(['P_' sreg]) * strys.(['IH_' sreg]);

        strys.(['KG_' sreg]) = strys.(['G_' sreg]) / strpar.deltaKG_p;
    end
end
